name: Maintainer Bot

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  reply_to_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run GraphQL Query
        uses: ./.github/actions/graphql-query
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          query: |
            {
              repository(owner: "${{ github.repository_owner }}", name: "${{ github.event.repository.name }}") {
                issues(last: 5) {
                  nodes {
                    title
                    url
                    createdAt
                  }
                }
              }
            }

      - name: Output query result
        run: echo "${{ steps.graphql-query.outputs.result }}"