name: Maintainer Bot

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  reply_to_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies for custom action
        run: npm install
        working-directory: .github/actions/graphql-query

      - name: Show repository owner with github-script
        uses: actions/github-script@v6
        with:
          script: |
            console.log("Repository owner:", process.env.GITHUB_REPOSITORY_OWNER || github.context.repo.owner);

      - name: Run GraphQL Query
        uses: ./.github/actions/graphql-query
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          query: |
            {
              repository(owner: "${{ github.repository_owner }}", name: "${{ github.event.repository.name }}") {
                issues(last: 5) {
                  nodes {
                    title
                    url
                    createdAt
                  }
                }
              }
            }

      - name: Output query result
        run: echo "${{ steps.graphql-query.outputs.result }}"
