name: Maintainer Bot

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  reply_to_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-comment on new issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "Thanks for opening this issue! The maintainers will take a look soon. 🙌"
            })
